export const Config = {
  SECRET: process.env.AUTH_SECRET,
  DISCORD_CLIENT: process.env.DISCORD_CLIENT,
  DISCORD_SECRET: process.env.DISCORD_SECRET,
  DISCORD_CLIENT_REDIRECT: process.env.DISCORD_CLIENT_REDIRECT,
  GOOGLE_CLIENT: process.env.GOOGLE_CLIENT,
  GOOGLE_SECRET: process.env.GOOGLE_SECRET,
  GOOGLE_CLIENT_REDIRECT: process.env.GOOGLE_CLIENT_REDIRECT
};
